### ISSUE TITLE
AccountIdNotSetException

### ISSUE THREAD

**Issue by barrymac** [jenkinsci/google-cloudbuild-plugin#6]
The documented syntax appears unfamiliar to me, with the trailing slash 
`googleCloudBuild \`

I get a AccountIdNotSetException despite adding it as currently documented

**Comment by bwkimmel** [comment]
The trailing slash in the example is required by the underlying Groovy syntax so that the following line (containing the first parameter to googleCloudBuild) is treated as part of the same statement, rather than the beginning of a new statement. Alternatively, you could include the first parameter on the same line (after which the commas separating the parameters are sufficient to indicate to Groovy that the statement continues on the next line), or you could enclose the parameter list in parentheses.

The AccountIdNotSetException, though, is not related to the presence or absence of the trailing slash. This exception is thrown by the google-oauth-plugin. This suggests that the credential referred to by the "credentialsId" parameter to googleCloudBuild is not correctly configured.
